language: node_js
node_js:
- 6.4.0
notifications:
  email: false
before_install:
- travis_retry nvm install 5.5.0
- if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then npm install request; npm run update-package;
  fi
env:
  global:
  - MONGO_URI=mongodb://student:ilovetesting@ds139267.mlab.com:39267/comprehensive
  - POSTGRES_URI=postgres://efeitgbt:vtyVc1GbU5CSq3-QNdu5Tf5BgHGH28wB@elmer.db.elephantsql.com:5432/efeitgbt
script:
- if [ $TRAVIS_SECURE_ENV_VARS == "true" ]; then npm run get-test-utils && npm run
  test ; npm run lint ; npm run report; else npm run merge; fi
